# Generated by Django 2.1.2 on 2018-10-24 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
    ]
