# Generated by Django 2.1.1 on 2018-10-25 12:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20181024_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, verbose_name='time for test'),
        ),
    ]
