# Generated by Django 2.1.1 on 2018-10-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20181025_1552'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='test',
            managers=[
            ],
        ),
    ]
