# Generated by Django 2.1.1 on 2018-11-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20181025_1717'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='answer',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='result',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='useranswer',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='test_type',
            field=models.CharField(choices=[('th', 'teaching'), ('ex', 'exam')], default='th', max_length=2),
        ),
    ]
