# Generated by Django 2.1.1 on 2018-11-08 17:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time(0, 30), verbose_name='Max time for test'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='mainapp.Question'),
        ),
    ]
