# Generated by Django 2.1.1 on 2018-11-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20181108_1733'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='testcategory',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='order_number',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
        migrations.AddField(
            model_name='question',
            name='q_type',
            field=models.PositiveIntegerField(choices=[(0, 'Выбор'), (1, 'Мультивыбор'), (2, 'Порядок')], default=0, verbose_name='question type'),
        ),
        migrations.AlterField(
            model_name='test',
            name='max_questions',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Count questions'),
        ),
    ]
