# Generated by Django 2.1.2 on 2018-11-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20181117_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('select', 'Выбор правильного(-ых) ответа(-ов)'), ('sort', 'Ответы по порядку')], default='select', max_length=10, verbose_name='question type'),
        ),
    ]
